apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/<username>
  username: <username>
  password: <token>
