apiVersion: v1
kind: Secret
metadata:
  name: <secret-name>
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: git@github.com:<username>
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    # Private key content
    -----END OPENSSH PRIVATE KEY-----
