apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: default
spec:
  containers:
    - name: netshoot
      image: nicolaka/netshoot
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: "512i"
          cpu: "500m"
        requests:
          memory: "256Mi"
          cpu: "250m"
