server {
  listen                  80;
  listen                  [::]:80;

  server_name             example.com www.example.com;

  root                    /var/www/metabase;

  access_log              /var/log/nginx/metabase-access.log;
  error_log               /var/log/nginx/metabase-error.log warn;

 location / {
    include               proxy_params;
    proxy_redirect        off;
    proxy_pass            http://localhost:3000;
  }
  
  location /favicon.ico {
    access_log            off;
    log_not_found         off;
  }
}
