apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: admin-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "admin-sa"
# data:
#   token: |
#     ADMIN TOKEN IN BASE 64 ENCODED
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: developer-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: "developer-sa"
# data:
#   token: |
#     DEVELOPER TOKEN IN BASE 64 ENCODED
