adminPassword: admin

sidecar:
  enableUniqueFilenames: true
  dashboards:
    enabled: true
    provider:
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    # searchNamespace: ALL
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
    serve_from_sub_path: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        orgId: 1
        uid: tempo
        url: http://tempo-distributed-query-frontend.grafana.svc:3100
        isDefault: false
        editable: true
      - name: Loki
        type: loki
        access: proxy
        orgId: 1
        uid: loki
        url: http://loki-distributed-query-frontend.grafana.svc:3100
        isDefault: false
        editable: true
        jsonData:
          derivedFields:
            - datasourceName: Tempo
              matcherRegex: "traceID=(\\w+)"
              name: TraceID
              url: "$${__value.raw}"
              datasourceUid: tempo
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        uid: prometheus
        url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
        isDefault: false
        editable: true

persistence:
  enabled: true
  storageClassName: longhorn
  size: 5Gi
