bpf:
  hostLegacyRouting: true
cluster:
  name: my-cluster
cni:
  customConf: false
  uninstall: false
ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList:
    - 10.244.0.0/16
operator:
  replicas: 1
  unmanagedPodWatcher:
    restart: true
policyEnforcementMode: default
routingMode: tunnel
tunnelPort: 8473
tunnelProtocol: vxlan
